package br.edu.imepac.commons.dto;

import lombok.Data;

@Data
public class PacienteDTO {
    private Long id;
    private String nome;
    private String cpf;
    private String endereco;
    private Long convenioId; // Assuming you want to transfer only the ID of ConvenioModel

    // Constructor with fields
    public PacienteDTO(Long id, String nome, String cpf, String endereco, Long convenioId) {
        this.id = id;
        this.nome = nome;
        this.cpf = cpf;
        this.endereco = endereco;
        this.convenioId = convenioId;
    }

    // Empty constructor (if needed)
    public PacienteDTO() {
    }

    // Getters and setters as generated by Lombok
}