package br.edu.imepac.commons.dto;

import lombok.Data;

@Data
public class ProntuarioDTO {
    private Long id;
    private String descricao;

    // Constructor with fields
    public ProntuarioDTO(Long id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }

    // Empty constructor (if needed)
    public ProntuarioDTO() {
    }

    // Getters and setters as generated by Lombok
}